version: '3'

services:
        php:
                container_name: "php-fpm"
                build: "php"
                environment:
                        - APP_ENV=${APP_ENV}
                        - APP_SECRET=${APP_SECRET}
                volumes:
                        - ${APP_FOLDER}:/var/www
                stdin_open: true # docker run -i
                tty: true        # docker run -t

        nginx:
                container_name: "nginx"
                build:
                        context: ./nginx
                volumes:
                        - ${APP_FOLDER}:/var/www
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./logs:/var/log
                depends_on:
                        - php
                ports:
                        - "80:80"
                 
